### ISSUE TITLE
Wrong Terminal Command Listed

### ISSUE THREAD

**Issue by jonathonmcclen** [learn-co-curriculum/macos-env-nodejs#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas
https://learning.flatironschool.com/courses/1877/pages/installing-node-dot-js-on-macos?module_item_id=260638

## Describe the bug
in the listed steps we are told to "2. Type curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash and press <Enter>"
once this is done we are told to restart our terminal and then test that it works by typing "nvm" into the terminal. After trying this 3 times I tried to restart the computer. Still nothing. So I decided to watch the video that is imbedded. The video has you type a different command to install.

"curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | zsh"
"zsh" instead of "bash"

worked immediately. so this text should be changed.

## What OS are you using?

- [x] OS X

**Comment by graciemcguire** [comment]
Thanks for flagging this @jonathonmcclen ! We have made the change in the readme. Thanks!
